---
stages:
  - deploy

variables:
  APP_NAME: discoursio-api
  SERVER: v2.discours.io

deploy:
  image: alpine
  stage: deploy
  environment:
    name: production
    url: https://v2.discours.io
  only:
    - main
  script:
    - mkdir -p ~/.ssh
    - ssh-keyscan -t rsa $SERVER >> ~/.ssh/known_hosts
    - echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
    - chmod 0400 ~/.ssh/id_rsa
    - git remote add dokku dokku@$SERVER:$APP_NAME
    - git push dokku
