---
image: dokku/ci-docker-image

stages:
  - deploy

variables:
  GIT_DEPTH: 0

deploy:
  stage: deploy
  only:
    - main
  variables:
    # specify the `main` branch as the remote branch to push to
    BRANCH: main
    GIT_REMOTE_URL: ssh://dokku@staging.discours.io:22/discoursio-api
  script: dokku-deploy
  after_script: [dokku-unlock]
