---
stages:
  - deploy

variables:
  APP_NAME: discoursio-api

deploy:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment:
    name: production
    url: https://testapi.discours.io
  only:
    - main
  script:
    - git-push ssh://dokku@staging.discours.io:22/$APP_NAME
