---
stages:
  - deploy

variables:
  APP_NAME: discoursio-api

deploy:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment:
    name: production
    url: https://v2.discours.io
  only:
    - main
  script:
    - ssh-keyscan -t rsa v2.discours.io >> ~/.ssh/known_hosts
    - git-push ssh://dokku@v2.discours.io:22/$APP_NAME
