version: '3'

services:
  redis:
    image: redis:5.0.3-alpine
    container_name: redis
    ports:
    - 6379:6379

  server:
    image: discoursio/api:v0.0.1
    container_name: api
    ports:
      - 8002:24579
    command: ["python", "server.py"]
