name: 'Deploy to discoursio-api'
on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to discoursio-api
        uses: dokku/github-action@master
        with:
          ssh-private-key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          ssh-host: staging.discours.io
          ssh-user: dokku
          app-name: discoursio-api
          git-remote-url: ssh://dokku@staging.discours.io:22/discoursio-api
