name:  'Deploy to discoursio-api'
on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Repo Name
        id: repo_name
        run: echo "::set-output name=repo::$(echo ${GITHUB_REPOSITORY##*/})"

      - name: Get Branch Name
        id: branch_name
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF##*/})"

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: 'main'
          git_remote_url: 'ssh://dokku@v2.discours.io:22/discoursio-api'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}


