name: 'deploy'
on: 
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Branch Name
        id: branch_name
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF##*/})"

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          ssh-private-key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          ssh-host: staging.discours.io
          ssh-user: dokku
          app-name: ${{ steps.branch_name.outputs.branch == 'main' ? 'discoursio-api' : 'core' }}
          git-remote-url: ${{ steps.branch_name.outputs.branch == 'main' ? 'ssh://dokku@staging.discours.io:22/discoursio-api' : 'ssh://dokku@staging.discours.io:22/core' }}